### ISSUE TITLE
node bot.js

### ISSUE THREAD

**Issue by atikjaz** [asdofindia/telegram-updates-bot#1]
When I type `node bot.js` it shows modules not found. How to solve that. I searched on Google but didn't get answer.

**Comment by asdofindia** [comment]
I suppose you'll have to follow the instruction in the README.

Or alternatively, you have to post details on everything that you did including the error message.

And more importantly, this is a 5 year old project that isn't maintained anymore while Telegram Bots API has moved far in those years.
